iamnotturner/vaccipy

main.py
I don't think it's a problem but it's worth nothing that this requires Python 3.9: https://docs.python.org/3.9/library/stdtypes.html?highlight=removeprefix#str.removeprefix
=> Strip leading +49 and 0 from user input

main.py
Entfernt Leerzeichen am Anfang und Ende der eingegeben Wohnort PLZ und prüft, dass sie genau 5 Stellen lang ist und nur aus Ziffern besteht.
Das ist nicht rein kosmetisch, impfterminservice.de lehnt solche PLZ ab. 
> 2021-05-19 12:04:14.297  impfterminservice  [err] [***** | ******]  Termin konnte nicht gebucht werden: {‘error’: {‘plz’: ‘ungültig Länge’}}
=> Validiert die Eingabe der Wohnort PLZ

README.md
Apparently github assumes a relative link when protocol is omitted
=> Fixed doctors without borders link

main.py
This makes the currently hardcoded value of delay time between two consecutive attempts configurable, using a default value of 30 seconds, also to be backwards compatible.
In some cases (especially when running multiple instances of the script using the "profile" option) the default value of 30 seconds is too aggressive, leading to 429 responses from the remote server.
Basically there is just another optional command line argument `--retry-sec`:
```
% python3 main.py search -h
vaccipy - Automatische Terminbuchung für den Corona Impfterminservice
usage: main.py search [-h] [-f FILE] [--configure-only] [--retry-sec RETRY_SEC]
optional arguments:
-h, --help            show this help message and exit
-f FILE, --file FILE  Pfad zur JSON-Datei für Kontaktdaten
--configure-only      Nur …
```
=> Make the check_delay parameter configurable

shell.nix, tools/its.py
[cherry-pick of #103 against beta]
Discussion:
> apparently on Debian, installing beepy with pip requires the package python3-dev and libasound2-dev. Not sure what's required on other distros. So not sure if we want this feature. Can we make it optional, i.e. available if the user has beepy installed?
=> feat(beepy): Play coin sound when appointment is found

README.md, docs/distribution.md
Mir ist aufgefallen, dass man unter Linux die executables erst executable machen muss und dafür hab ich den passenden command schonmal convenience-mäßig in die docs eingefügt.
=> docs: Mehr info zum Ausführen der Executables unter Linux

tools/its.py
Wenn Beepy nicht funktioniert, wird versucht, stattdessen einen Piep über das BELL-Steuerzeichen auszugeben. Hat mir gerade einen Termin gerettet.
=> BELL-Fallback für Beepy

tools/its.py
Siehe https://github.com/iamnotturner/vaccipy/pull/164#issuecomment-849154822
Wenn Beepy nicht funktioniert, wird versucht, stattdessen einen Piep über das BELL-Steuerzeichen auszugeben. Funktioniert nicht in allen Terminals, aber z. B. mit iterm2 auf OS X. Wird es von einem Terminal nicht unterstützt, passiert einfach gar nichts.
=>  BELL-Fallback für Beepy

README.md
Fix: Grammar: Plural words in Germany don't take an apostrophe.
I also removed obsolete empty lines - and added when recommended by [markdown lint's rules](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md)
=> Fix Apostroph

README.md
Die Links bei den Icons waren veraltet. Siehe #180
Ist nun jeweils beides auf [https://github.com/iamnotturner/vaccipy/releases/latest](https://github.com/iamnotturner/vaccipy/releases/latest)
=> Fixed: Release links in README

tools/its.py
Mails kommen oftmals nicht an, wenn Mail große Buchstaben enthält
=> mail kleingeschrieben bei code generierung

tools/its.py
Cookies generieren und Login gelöscht bei Terminsuche, da nicht benötigt.+
Nach jedem Requests werden Cookies gelöscht mit der Hoffnung dass dadurch besser Termine gefunden werden. Hatte heute wieder den Fall dass alte Sessions keinen Termin gefunden haben und manuell 10 Minuten Termine verfügbar waren.  Gefahr besteht dass mit ständigem Cookie löschen nichts mehr gefunden wird. Muss man probieren.
=> flow improvements

README.md, tools/its.py
There might be several reason why someone wants to specific the path of the chrome bin (e.g. snap, having a special setup for `chrome` in PATH, ...).
So here a simple pull request to add the option to specify the chrome bin via an envvar.
=> Allow to specify chrome bin via envvar

tools/gui/qtkontakt.py, tools/gui/qtterminsuche.py, tools/gui/qtzeiten.py
I found the cause of the colour codes in the GUI and replaced them with an empty string. 
This removes any non-displayable characters in the GUI (stdout).
**Before:**
**Afterwards**
This is my first pull request. I hope I have not made a mistake :)
=> Fixed colour codes in gui + some spelling mistakes in comments

gui.py, tools/gui/main.ui, tools/gui/qtterminsuche.py, tools/gui/terminsuche.ui
With @Floskinner 's support, I have added the dynamic setting of the delay between the appointment search to the GUI version.
This PR has probably solved this: #234
**This includes:**
- Setting the delay between 30 and 300 seconds (smaller or larger values aren't possible)
- Passing the time to 'qtterminsuche.py' to display it there
- A different waiting time can be set for each individual search process
=> Dynamic setting of the delay between the appointment search

main.py, tools/gui/qtterminsuche.py, tools/gui/qtzeiten.py, tools/gui/uhrzeiten.ui, tools/its.py, tools/kontaktdaten.py
In ImpfterminService, rename `zeitspanne` to `zeitrahmen` and change its format to be more user-friendly. Also, make it possible to configure this `zeitrahmen` via the `.zeitrahmen` field of `kontaktdaten.json` and via the CLI. As before, one can construct a fully-featured `kontaktdaten.json` via the CLI.
This commit also adapts the GUI to pass the new format to the ImpfterminService. However, it will need further changes to migrate from `zeitspanne.json` to `kontaktdaten.json`, so that GUI and CLI use the same storage format.
**Note: GUI is currently untested**, cause I didn't get it to run, yet.
=> feat(zeitrahmen): Add new zeitrahmen field for CLI

main.py, tools/kontaktdaten.py
Fix duplicate definition of `class ValidationError`. This fixes a bug where the exception was not caught, because those two are different Python types.
Also validate that dates and times aren't in wrong order.
=> fix(validation): Fix dup. def. of class ValidationError

main.py, tools/kontaktdaten.py
In the CLI, for certain "zeitrahmen" subfields, allow to skip them by entering the empty string.
=> feat(zeitrahmen): In CLI, allow to skip zeitrahmen-subfields

tools/gui/impfzentren.ui, tools/gui/kontaktdaten.ui, tools/gui/qtimpfzentren.py, tools/gui/qtkontakt.py, tools/gui/qtzeiten.py, tools/utils.py
New Feature
-
Man muss nun nicht mehr die ganzen PLZs der Impfzentren manuel raussuchen + sieht direkt welche Impfzentren gruppiert sind
- Die Impfzentren können nun direkt in der GUI ausgewählt werden
- Alle Impfzentren werden dynamisch hinzugefügt ( immer up-to-date )
- Nur die PLZs der gleichen Gruppe können hinzugefügt werden
- Neue Funktion in der `utils.py` - `get_grouped_impfzentren` - Danke an @iamnotturner  für den Code, hat mein Leben sehr erleichtert!
Bilder
-
Neuer Button:
---------
Übersicht aller Zentren:
---------
Wählt meine eine Gruppe aus, sind die anderen gesperrt
---------
Importieren in das Eingabefeld
Tests
-
Tests waren alle erfolgreich und kann direkt ge-merged werden :)
=> [Feature]: Impfzentren können direkt in der GUI ausgewählt werden

tools/kontaktdaten.py
Fix for #268 
Die GUI ist noch nicht vollständig auf die neue Zeitspanne umgestellt, daher fehlt immer der Key `zeitspanne` in dem `kontaktdaten.json`
Deshalb vorübergehend die Überprüfung auf das Feld auskommentiert
=> Fix(kontakdaten - GUI): Speichern von Kontaktdaten nicht möglich da ein Key Fehlt

tools/its.py
This is usually much faster than waiting if skipping fails once.
=> feat(warteraum): Retry skip every 5 sec

tools/its.py
Appointments outside the time frame are now displayed as a warning. 
This makes it easier to notice if you want to book the appointment manually for another person, for example.
I have also added dividing lines to make them more visually separable.
=> Show appointments outside the time frame as a warning

tools/gui/qtimpfzentren.py
Die Gui konnte nicht unter Python 3.8 ausgeführt werden da ein typing verwendet wurde, welches erst in 3.9+ implementiert wurde.
Vorlage von #284 verwendet
=> fix(typing): fixed typing for python < 3.9

gui.py
Wenn keine version.txt vorhanden ist, startet das GUI nicht
...hab ich bei #342 übersehen
=> fix(gui version): Absturz wenn version.txt nicht vorhanden

gui.py, tools/gui/qtkontakt.py
Problem
-
Aktuell ist es so, dass wenn man bei der Auswahl einer anderen JSON-Datei auf "x"- Drückt das GUI crashed:
---
Problem wurde nun behoben
Bitte auch noch #348 mergen, da dies bei direktem clonen des Repo zu einem crash des GUI führt
=> fix(GUI Pfadauswahl): GUI stürz beim "x" drücken während der Pfadauswahl ab

tools/its.py
Fixed NameError exception due to quit() call. Replaced with sys.exit().
reference: https://docs.python.org/3.8/library/constants.html#quit
Tested in Linux-Ubuntu-20.04 build.
=> fix(Falsche PLZ): Fixed NameError exception #367

tools/kontaktdaten.py
Hi,
Gmail erlaubt das Plus-Zeichen (z.b., max-mustermann+impfung_oma@gmail.com), siehe https://support.google.com/a/users/answer/9308648?hl=en
Der Impfterminservice lehnt das aber ab, was ärgerlich ist, falls es erst beim Buchen auffällt.
--> Email-Validierung um mögliche Plus-Zeichen erweitert
=> Emails mit "+" ablehnen

gui.py, main.py, tools/exceptions.py, tools/gui/qtkontakt.py, tools/gui/qtterminsuche.py, tools/its.py, tools/kontaktdaten.py
Mit diesem Commit kann man mehrere Codes im `"codes"`-Key der Kontaktdaten angeben. Es werden dann automatisch Codes zu Servern (im Quellcode üblicherweise `url` genannt) zugeordnet. Außerdem ist es nun erlaubt serverübergreifende PLZs anzugeben. Es wird dann auf jedem nötigen Server (`url`) nach Terminen gesucht.
Hierzu speichert der Bot intern die Datenstrukturen
- `self.codes`
- `self.cookies`
- `self.impfzentren`
- `self.verfuegbare_qualifikationen`
jeweils nach `url` gruppiert, d. h. in einem `dict` mit `url` als Key.
Dies ist ein Draft, da es noch mehrere TODOs gibt:
Bei mir läuft die Terminsuche, aber ob auch die Terminbuchung klappen würde kann ich nicht sagen, da ich aktuell keine Termine finde.
Bei der Code-Anfrage laufe ich gerade immer in die Botprotection. Liegt das daran, …
=> feat(code): Allow to specify multiple codes

tools/its.py
Dies hilft, die Buchung zu sehen oder manuell zu beenden, falls der Bot das nicht schafft.
=> feat(search): Immer Link zur Buchung loggen

main.py
Wenn durch fehlerhafte Eingabe von z.B. einem API-Tokens ein Fehler beim senden des Validierungscodes auftritt, wird dieser nun abgefangen.
Davor führte eine Exception dazu, dass die gesamte Eingabe der Kontaktdaten von vorne gestartet wird.
=> fix(notify): catch exception of pushover and telegram validation

tools/its.py
Wie man am Kommentar sieht, tauchen immer wieder neue Response-Inhalte auf, die darauf hindeuten, dass das Terminpaar nicht mehr gebucht werden kann. Gemein haben sie, dass der Status Code 400 lautet. In meinen Tests war es bisher so: Immer, wenn ein 400er zurueck kommt, ist das Terminpaar auch manuell nicht buchbar, da es nicht mehr verfuegbar ist.
=> fix(search): Interpretiere alle 400er als AppointmentGone

tools/its.py
Ein "Codepoint" ist ein dict, das einen Vermittlungscode (`"code"`) und den Zeitpunkt (`"next_use"`) enthält, zu dem der Code frühestens verwendet werden soll. So kann man die Verwendung eines Codes z. B. für 10 Minuten unterbinden.
=> feat(search): Wenn angebracht, pausiere Vermittlungscodes

tools/its.py
On Linux, the backslash in `tools\\log\\` was not interpreted as path separator, so screenshots etc. ended up in the project's root directory, named `tools\log\<filename>`. Now they are named `<filename>` and stored in the `log`-directory under `tools`.
=> fix(log): Ensure tools/log paths are constructed portably

gui.py, tools/gui/__init__.py, tools/gui/qtkontakt.py
Es wird keine Fehlermeldung mehr angezeigt, wenn das Laden von Kontaktdaten in der UI durch den Benutzer abgebrochen wird.
=> fix(GUI error pop up): Don't throw and show error if loading of data was cancelled by the user

requirements.txt, tools/its.py
~~Added function which generates a random curve and returns the corresponding x and y coordinates.~~ 
~~Those coordinates are used to simulate the mouse movement.~~ 
~~Added optional cookie entries~~
~~With > 50 simulated mouse movements the bot protection was fooled most of the times. Works not in 100% of the cases but should improve the chances.~~
Edit:
- Funktion welche zufällige Wegpunkte zwischen Quell x,y und Ziel x,y erzeugt
- Funktion welche eine Liste von x/y Koordinaten abfährt
- Funktion die beide Funktionalitäten kapselt und die Maus von start x,y zu Ziel x,y fahren lässt
- V-Code wird jetzt char für char eingegeben
- Falls "Es ist ein unerwarteter Fehler aufgetreten" eintritt wird jetzt direkt noch ein zweites mal auf Terminsuche geklickt, manchmal funktioniert das
-> Maus …
=> fix(cookie-gen): Improve cookie generation / enter v-code with updated mouse simulation

main.py
In order to avoid overloading the servers, I have set a minimum of 30 seconds for the value of retry-sec. 
This is the same value as for the GUI.
=> Limit retry-sec / check-delay

main.py, requirements.txt, tools/its.py
Vermittlungscode Anfrage via Selenium.
Wenn im SessionStorage "ets_session_its_cv_quick_check" = {"birthdate":"'+ data["birthday"] +'","slotsAvailable":{"pair":true,"single":false}} gesetzt ist, kann impftermine/check direkt aufgerufen werden.
Anschließend automatisch mail und phone eingeben und Anfrage in Selenium stellen.
Um die Antwort aus Selenium lesen zu können wurde selenium-wire verwendet.
Das ist erstmal nur ein Entwurf. 
Kann bitte jemand prüfen ob so ein Vermittlungscode erzeugt werden kann ? (Habe das Anfrage Limit erreicht und online Handynummern / sms scheinen nicht mehr zu gehen)
Falls nach der Eingabe des SMS codes wieder 429 kommt muss der sms code eventuell auch in selenium eingegeben werden. Das konnte ich noch nicht testen.
=> Workaround für Generierung von Vermittlungscodes

tools/its.py, tools/utils.py
Da es ja derzeit vermehrt auftritt, dass Termine nicht automatisch gebucht werden (können), habe ich mal hinzugefügt, dass die Notifications direkt nachdem ein passender Termin gefunden wurde, gefeuert werden. Der Link zur manuellen Buchung wird gleich mit gesendet, somit hat man dann die Chance rechtzeitig manuell einzugreifen. Dank der Telegram Anbindung auch unterwegs...
=> feat(notifications): Fire notification as soon as an appointment was found

main.py, tools/its.py, tools/utils.py
Mit dem neuen Modul `undetected_chromedriver` ist es nicht mehr notwendig, die Chromedriver-Binaries lokal zu speichern. Es gibt drei Möglichkeiten für Chromium & die Chromedriver:
1. Google Chrome installieren (`undetected_chromedriver` findet Chromium und den Chromedriver von selbst)
2. Installation mit `./tools/chromium_downloader.py` oder Option 3 im Vaccipy-Menü
3. Pfad über Umgebungsvariablen festlegen: `VACCIPY_CHROME_BIN` (Chromium) und `VACCIPY_CHROMEDRIVER` (Chromedriver)
Todos:
=> feat(local-chromium): replacing chromedriver binaries with google chrome or custom chromium installation
