iamnotturner/vaccipy

main.py

Getestet mit dem Impfzentrum 70174 Stuttgart Liederhalle

URL Änderungen April

---

.gitignore
main.py

Hi Tim,
I came across your repo and wanted to contribute, as I have started a similar project some days ago.
Adjustments: 
- send the whole code as it is works totally fine 
- gitignore updates 
Tested on Windows

minimalized code input

---

main.py

Note: I did not test this again since I don't want to risk being sent back to the waiting queue. But it's based on the code I'm already using so it *should* work...
fixes #9

Deal with bogus appointments

---

main.py

see #8 for details. I still have no clue how exactly it's determined whether a particular request does to the waiting room... maybe it'd be better to get a new cookie if we are in the queue for too long... but implementing a sliding window to see if we've been in the waiting room N times in a given period is not something I want to do, especially without knowing that it's actually useful :D
```
2021-05-02 21:51:06.658   impfterminservice   [inf] [*XXXX]   Keine Termine verfügbar: {'gesuchteLeistungsmerkmale': ['L920'], 'termine': [], 'termineTSS': [], 'praxen': {}}
Waiting room... retrying in a bit
Waiting room... retrying in a bit
Waiting room... retrying in a bit
Waiting room... retrying in a bit
Waiting room... retrying in a bit
Waiting room... retrying in a bit
Waiting room... …
```

Handle waiting room during appointment search

---

main.py

https://docs.python.org/3/library/platform.html

updated linux architecture check

---

main.py

[cherry-pick of #81 against beta]
Currently the supported subcommands are:
* search (either interactive oder non-interactive via --file)
* configure (interactive generation of kontaktdaten JSON file, also supports --file)
* code (interactive generation of Vermittlungscodes)

feat(argparse): Add argument parser supporting 3 subcommands

---

README.md
main.py

Cherry-pick of #78 against beta.

feat(chromedriver): Allow to specify chromedriver via envvar

---

main.py

This is a commit intended mostly for debugging.  I'm interested in whether the users experiencing issue #80 obtain a 429 status code.

chore(booking): Check for 429 and log it

---

shell.nix

feat(nix): Add shell.nix for Nix support without venv

---

main.py

To disable this behaviour, use the new flag `--read-only`.

feat(argparse): -f/--file now supports interactive input

---

main.py

feat(expert-mode): Make new options (#83, #97, #98) available interactively

---

tools/its.py

WARNING: This is untested, because I didn't find an appointment since coding this.

fix(booking): Use correct plz when booking via selenium

---

main.py

Warning: This is untested.
Edit:
Fixes #114

fix(kontaktdaten.json): Try to fix utf-8 problems

---

tools/its.py

Reverts iamnotturner/vaccipy#164

Revert "BELL-Fallback für Beepy"

---

main.py

Added note to only enter the street name (not the number)
to avoid incorrect data and forcing users to restart the process.
Signed-off-by: Lenz Grimmer <lenz@grimmer.com>

main.py: Improved message when entering personal data

---

.gitignore
tools/its.py

Logging bei Screenshot error + Screenshots bei fehlgeschlagener Terminsuche und Dateneingabe

Seleniumlog

---

requirements.txt

Hier ist die angepasste requirments.txt

Updated requirments.txt

---

tools/gui/main.ui
tools/gui/terminsuche.ui

There were some minor typos in the GUI window

Typos in GUI corrected

---

main.py
tools/exceptions.py
tools/gui/__init__.py
tools/kontaktdaten.py

Wir haben ja eine eigene Datei wo wir die Exceptions alle auflisten... :)
(In meiner GUI Anwendung ist auch noch eine, die fliegt aber bald raus)

Exception ausgelagert

---

README.md
impfzentren_gruppiert.md
main.py

Bugfix um zufallsbasiert die PLAT-ZHAL-TER1 zu generieren ;-) 
https://github.com/iamnotturner/vaccipy/issues/238#issuecomment-851497794

Random generation of PLATZHALTER

---

main.py

Should use a proper IDE for this ... @iamnotturner

Use existing variable

---

main.py

Fix missing import string in 23e7713 

---

main.py

Spelling fixes

---

tools/its.py

fix(zeitrahmen): More fixes, inspired by #267

---

tools/its.py

@iamnotturner Ich konnte nun endlich testen und so weitere Bugs identifizieren. Mit diesem Commit funktioniert es.

fix(zeitrahmen): Convert datetime to date/time when needed

---

requirements.txt
specs/windows-terminservice-gui.spec

fix für #277 
Ich habe vergessen die neue Datei in die spec datei mit aufzunehmen...

fix(impfzentren anzeigen) - Anzeigen der Zentren fürt zu keinem Absturz mehr 

---

tools/its.py

2021-06-03 21:31:57.867   impfterminservice   [inf] [*JNHV | 74549, 74585]   Browser-Cookies generieren
2021-06-03 21:31:59.815   impfterminservice   [inf] [*JNHV | 74549, 74585]   Code eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
=> geht nicht weiter
2021-06-03 21:31:57.867   impfterminservice   [inf] [*JNHV | 74549, 74585]   Browser-Cookies generieren
2021-06-03 21:31:59.815   impfterminservice   [inf] [*JNHV | 74549, 74585]   Code eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-03 21:32:06.209   impfterminservice   [inf] [*JNHV | 74549, 74585]   Browser-Cookie generiert: *W8gA==

Browsercookiefail

---

tools/its.py

Some Xpath adaptions to more generic

fix(xpath): reduce path levels

---

main.py
tools/its.py
tools/utils.py

Git Hub Rate Limited => Versions Check bei Suche ausgebaut

fix(Version): Fix print output

---

README.md
gui.py
main.py
tools/gui/qtkontakt.py
tools/kontaktdaten.py
tools/utils.py

- ~~Bekanntes Problem: bei fehlerhafter Eingabe wird nicht die gesamte pushover oder telegram Eingabe von vorne gestartet. Die Struktur von input_kontaktdaten_key macht das schwierig.~~

feat(Notification): better validation

---

tools/its.py

https://github.com/iamnotturner/vaccipy/issues/422
Wie hier vorgeschlagen gibt nun vaccipy eine Info nach erfolgreicher Terminbuchung aus.
Diese macht auf die Kampagne von Ärzte ohne Grenzen aufmerksam.
Finde ich eine gute Idee, weil dadurch mehr Leute darauf aufmerksam gemacht werden.

Added donation url after booking was successfull

---

docs/distribution.md
specs/windows-terminservice-gui.spec

Please try a test build for windows and start codegen

Fix Code Gen not starting with windows builds

---

tools/gui/kontaktdaten.ui

Kind and Divers are now also selectable ,)

Added Kind and Divers to GUI

---

tools/gui/kontaktdaten.ui

Reverts iamnotturner/vaccipy#437

Revert "Added Kind and Divers to GUI"

---

tools/gui/kontaktdaten.ui

Kind and Divers are now also selectable ,)
This is replacement for[#437 ]( https://github.com/iamnotturner/vaccipy/pull/437)

feat(gender GUI): Added Kind and Divers

---

tools/its.py

refactor(search): Rotiere durch PLZs, anstatt Zufallswahl

---

tools/gui/kontaktdaten.ui
tools/gui/qtkontakt.py

Gewünscht in #447
Alter PR #462 
@Floskinner 
> Beim "Zurücksetzten" werden die Codes noch nicht zurückgesetzt / gelöscht.
Habe ich eingebaut.
> Macht mich auch irgendwie Stutzig, dass so viele Änderungen angezeigt werden obwohl die doch schon in der Beta sind (zB die automatische Sprache der Buttons)
> Das hatten wir hier schon einmal und dann wurden aus versehen alte Zustände wiederhergestellt. Bekommst du das evtl. hin, dass wirklich nur die relevanten Änderungen angezeigt werden? 🤔
Habe das gecleant, musste dazu einen neuen Branch und daher auch einen neuen PR erstellen.

feat(notify): added notification configuration to GUI

---

main.py
tools/its.py

+ User wird jetzt über den aktuellen Status im Browser informiert
+ User kann SMS-Code jetzt direkt im Browser eingeben

Improve selenium vcode generation

---

gui.py
tools/gui/qtterminsuche.py

Beim letzten PR hat leider was gefehlt.

fix(notifications): not working in GUI

---

tools/its.py

Generate strings, not arrays of chars.

fix(random code): Fix creation of random code

---

README.md

Added completed Termineingrenzung feature to readme.

fix(readme): Termineingrenzung Feature in Readme eingefügt.

---

README.md
main.py

This led to errors when running `python3 main.py code --configure-only -f max-mustermann.json`.

fix(args): add missing configure_notifications argument
